### ISSUE TITLE
Required Indicator not visible

### ISSUE THREAD

**Issue by Juchar** [vaadin/vaadin-text-field-flow#113]
The required indicator is not visible, even if calling `setRequiredIndicatorVisible(true)`. 

Having a look at the HTML, it seems that the `opacity` of the `::after` pseudo element is set to `0`:
```CSS
[part="label"]::after {
    content: var(--lumo-required-field-indicator, "•");
    transition: opacity 0.2s;
    opacity: 0;
    color: var(--lumo-primary-text-color);
    position: absolute;
    right: 0;
    width: 1em;
    text-align: center;
}
```

Alternatively it could be that a `:host([required]) [part="label"]::after` style that is missing?
```CSS
:host([required]) [part="label"]::after {
    opacity: 1;
}
```
